apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-user: LW0gbW9uZ291c2VyCg== # mongouser in base 64
  mongo-password: LW0gbW9uZ29wYXNzd29yZAo= # mongopassword in base 64
